wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.7.16
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1708887154.096592
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 63
      3:
      - 17
      - 23
      - 24
      - 37
      4: 3.7.16
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
